---
title: "risk_characterization_tcdd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

```{r}
d <- read_csv("arsenic.csv")

d$logconc <- log10(d$Conc)

d$logRR <- log10(d$RR)

d$logconc2 <- d$logconc^2

arsenic_mod <- lm(logRR~logconc2+logconc,data=d)

newdat<-data.frame(logconc=seq(0,3,0.1))

newdat$conc <- 10^newdat$logconc

newdat$logconc2 <- newdat$logconc^2

pred_mod0 <- predict(arsenic_mod, newdata = newdat, interval = "confidence")

fit <- data.frame(mconc=newdat$conc,med_val=pred_mod0[,1],lo_val=pred_mod0[,2],hi_val=pred_mod0[,3])

p1 <-ggplot() + 
  geom_point(aes(x=Conc,y=logRR),data=d,shape=2)+ 
  geom_line(aes(x=mconc,y=med_val),data=fit,size=2) +
  geom_line(aes(x=mconc,y=lo_val),data=fit,linetype=2) +
  geom_line(aes(x=mconc,y=hi_val),data=fit,linetype=2) +
  scale_x_log10("ArsenicConc.(ug/L)",limits=c(1,1000),breaks=c(1,3,10,30,100,300,1000)) + 
  scale_y_continuous("Log10RelativeRisk",limits=c(-0.4,1),breaks=c(-0.4,-0.2,0,0.2,0.4,0.6,0.8,1))

print(p1)



```

